name: Prevent Supabase DB Pause

on:
  schedule:
    - cron: "0 0 * * *" # Everyday at midnight UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          curl -X GET \
            "$SUPABASE_URL/rest/v1/book?apikey=$SUPABASE_KEY"

      - name: Update Dummy Name with UUID
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          RANDOM_NAME=$(uuidgen)
          echo "Generated UUID: $RANDOM_NAME"

          RESPONSE=$(curl -s -w "\n%{http_code}" -X PATCH "$SUPABASE_URL/rest/v1/dummy?id=eq.1" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"name\": \"$RANDOM_NAME\"}")

          BODY=$(echo "$RESPONSE" | head -n 1)
          STATUS=$(echo "$RESPONSE" | tail -n 1)

          echo "HTTP Status: $STATUS"
          echo "Response Body: $BODY"
