name: Prevent Supabase DB Pause

on:
  schedule:
    - cron: "0 0 * * *" # Everyday at midnight UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-Alive Request
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          curl -X GET \
            "$SUPABASE_URL/rest/v1/book?apikey=$SUPABASE_KEY"
